### ISSUE TITLE
Wrong repository link in the installation instructions/description

### ISSUE THREAD

**Issue by BKirev** [modulr/api-laravel-passport#3]
`$ git clone https://github.com/modulr/api-laravel.git`

instead of

`$ git clone https://github.com/modulr/api-laravel-passport.git`

Tried to save some time by using this, instead of doing it myself. Ended up spending more time until I realize what's going on.

**Comment by alfredobarron** [comment]
Hello @BKirev thanks for your contribution, I hope it helps you this repo.
